language: python

python:
 - "3.5"

env:
 - DJANGO_VERSION=1.11.5

install:
 - pip install -r requirements.txt

before_script:
 - django-admin startproject testsite .
 - python manage.py migrate
 - ln -s zsolthajdu/django_pageinfo pageinfo

script:
 - python manage.py pageinfo.test