language: python

python:
 - "3.5"

env:
 - DJANGO_VERSION=1.11.5

install:
 - pip install -r requirements.txt

before_script:
 - django-admin startproject testsite .

script:
 - python manage.py django_pageinfo.test