language: python

python:
 - "3.5"

env:
 - DJANGO_VERSION=2.0.3

install:
 - pip install -r requirements.txt

before_script:
 - django-admin startproject testsite .
 - python manage.py migrate
 - ln -s zsolthajdu/django_pageinfo/pageinfo pageinfo
 - echo "INSTALLED_APPS += [ 'rest_framework', 'pageinfo']" >> testsite/settings.py
 - sed -i -e "s/^]/   path( 'pageinfo/'\, include('pageinfo.urls')),\n]/" testsite/urls.py
 - sed -i -e "s/import path/import path,include/" testsite/urls.py
 
script:
 - python manage.py test pageinfo.tests
