language: python

python:
 - "3.5"

env:
 - DJANGO_VERSION=1.11.5

install:
 - pip install -r requirements.txt

before_script:
 - django-admin startproject testsite .
 - python manage.py migrate
 - ln -s zsolthajdu/django_pageinfo pageinfo
 - echo "INSTALLED_APPS += [ 'rest_framework', 'pageinfo']" >> testsite/settings.py
 - sed -i -e "s/^]/   url\(r\'\^\'\, include\(\'pageinfo\.urls\'\)\)\,\n]/" testsite/urls.py
 
script:
 - python manage.py test pageinfo.tests
